---
- hosts: localhost

  roles:
    - andrewrothstein.yq

  tasks:

    - ansible.builtin.apt:
        pkg:
          - jq
          - libicu-dev # needed by cyclonedx
          - net-tools # for netstat et al
          - shellcheck
          - telnet
          - vim
          - zip

    - ansible.builtin.command: /home/linuxbrew/.linuxbrew/bin/brew install cyclonedx/cyclonedx/cyclonedx-cli
    - ansible.builtin.command: /home/linuxbrew/.linuxbrew/bin/brew install cdxgen

    - ansible.builtin.file:
        path: /root/.local/bin
        state: directory
        mode: '0755'
